apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-control
  template:
    metadata:
      labels:
        app: panel-control
    spec:
      containers:
      - name: panel-control
        image: panel-control:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: panel-control-service
spec:
  type: NodePort
  selector:
    app: panel-control
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000